#!/usr/bin/env bash
set -uo pipefail

# Scan all running Docker container images with Trivy for HIGH/CRITICAL vulnerabilities.
# Designed for weekly cron — always exits 0 (cron-safe).

# Source platform env for ALERT_REPO and GITHUB_TOKEN
if [[ -f /opt/platform/.env ]]; then
  # shellcheck source=/dev/null
  source /opt/platform/.env
fi

echo "=== Image Vulnerability Scan — $(date -Iseconds) ==="

if ! command -v trivy &>/dev/null; then
  echo "WARNING: Trivy is not installed. Skipping scan."
  exit 0
fi

# Get unique images from running containers
IMAGES=$(docker ps --format '{{.Image}}' | sort -u)

if [[ -z "$IMAGES" ]]; then
  echo "No running containers found."
  exit 0
fi

TOTAL=0
VULNERABLE=0
VULNERABLE_IMAGES=""

while IFS= read -r image; do
  ((TOTAL++))
  echo
  echo "--- Scanning: ${image} ---"
  if trivy image --severity HIGH,CRITICAL --no-progress "${image}" 2>&1; then
    :
  else
    echo "WARNING: Failed to scan ${image}"
  fi

  # Check if any HIGH/CRITICAL vulnerabilities were found
  VULN_COUNT=$(trivy image --severity HIGH,CRITICAL --no-progress --format json "${image}" 2>/dev/null \
    | grep -c '"VulnerabilityID"' || true)
  if [[ "$VULN_COUNT" -gt 0 ]]; then
    ((VULNERABLE++))
    VULNERABLE_IMAGES="${VULNERABLE_IMAGES}\n- **${image}**: ${VULN_COUNT} HIGH/CRITICAL vulnerabilities"
  fi
done <<< "$IMAGES"

echo
echo "=== Scan Complete ==="
echo "Images scanned: ${TOTAL}"
echo "Images with HIGH/CRITICAL vulnerabilities: ${VULNERABLE}"

# Create GitHub Issue if vulnerabilities found and alerting is configured
if [[ "$VULNERABLE" -gt 0 ]] && [[ -n "${ALERT_REPO:-}" ]] && command -v gh &>/dev/null; then
  ISSUE_TITLE="Alert: Image vulnerabilities detected"

  # Check for existing open issue (dedup)
  EXISTING=$(gh issue list --repo "$ALERT_REPO" --state open --search "$ISSUE_TITLE" --json number --jq '.[0].number' 2>/dev/null || true)

  if [[ -z "$EXISTING" ]]; then
    ISSUE_BODY="## Image Vulnerability Scan Alert

**Scan time**: $(date -Iseconds)
**Images scanned**: ${TOTAL}
**Images with vulnerabilities**: ${VULNERABLE}

### Affected Images
$(echo -e "$VULNERABLE_IMAGES")

### Recommended Actions
1. Review the vulnerable images with \`trivy image --severity HIGH,CRITICAL <image>\`
2. Update base images or apply patches
3. Re-deploy affected services

_Generated by \`scan-images.sh\` weekly cron_"

    gh issue create --repo "$ALERT_REPO" --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --label "security" 2>/dev/null \
      && echo "GitHub Issue created in ${ALERT_REPO}" \
      || echo "WARNING: Failed to create GitHub Issue"
  else
    echo "Open issue #${EXISTING} already exists — skipping issue creation"
  fi
fi

exit 0
